apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-static
  namespace: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 684673518097.dkr.ecr.us-east-2.amazonaws.com/k8s-static:1
        ports:
        - containerPort: 80